### ISSUE TITLE
how to get model_path

### ISSUE THREAD

**Issue by Zoehanlu** [yuewang-cuhk/TAKG#1]
Hello,i am a raw hand, i don't know how to get "the warmed up ntm model path" in
`python train.py -data_tag Weibo_s100_t10  -copy_attention -use_topic_represent -load_pretrain_ntm  -joint_train  -topic_attn -check_pt_ntm_model_path [the warmed up ntm model path]' , and 
"seq2seq model path" and "ntm model path" in 
`python predict.py -model [seq2seq model path] (-ntm_model [ntm model path]).

**Comment by yuewang-cuhk** [comment]
Hi, you need to pre-train ntm model first using `python train.py -data_tag Weibo_s100_t10 -only_train_ntm -ntm_warm_up_epochs [epoch_num, e.g., 100]`

**Comment by Zoehanlu** [comment]
I did it , and i got files like "Weibo_s100_t10.seed9527.emb150.vs50000.dec300.20191104-194249".

**Comment by yuewang-cuhk** [comment]
Under this folder, there should be some pre-trained NTM Models. In our paper, we choose the one that has been pre-trained for 100 epochs.
