### ISSUE TITLE
how to predict model

### ISSUE THREAD

**Issue by YichaoLuo** [yuewang-cuhk/TAKG#2]
Hi，when i predict model use this config：
_python predict.py -model ./model/Weibo_s100_t10.copy.seed9527.emb150.vs50000.dec300.20191111-204118/e4.val_loss=1.432.model-0h-04m_
error：
_assert opt.model.count('/') == 2 and all([tag in opt.model for tag in ['vs', 'emb', 'dec', 'model']])_
Should i add some configs？

**Comment by yuewang-cuhk** [comment]
Hi, it should be OK if you change the model file path into `model/Weibo_s100_t10.copy.seed9527.emb150.vs50000.dec300.20191111-204118/e4.val_loss=1.432.model-0h-04m` 
I hard code some usage functions according to my personal habit. Please feel free to revise it as you like:)

**Comment by YichaoLuo** [comment]
ok！Thank you very much！
