### ISSUE TITLE
How to get theta and phi?

### ISSUE THREAD

**Issue by lhy2749** [yuewang-cuhk/TAKG#3]
thanks for your code.And could you please tell me how to get the θ(topic-document) and the φ(topic-words)?(only for topic model)

**Comment by yuewang-cuhk** [comment]
Hi, for the topic-words, you can refer to line 247 of `pykp/model.py`. It is in the `self.fcd1.weight`.
For document-topic, we provide two ways to represent theta: g or z in line 244 of `pykp/model.py`.

**Comment by lhy2749** [comment]
thank you very much!
i will try to get them
