### ISSUE TITLE
Jointly train error?

### ISSUE THREAD

**Issue by zk1127** [yuewang-cuhk/TAKG#5]
when I run the `python train.py -data_tag Weibo_s100_t10 -copy_attention -use_topic_represent -load_pretrain_ntm -joint_train -topic_attn -check_pt_ntm_model_path [my ntm model path]`,come to the error `RuntimeError: Invalid index in scatterAdd at /tmp/pip-req-build-4baxydiv/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721`.the 'my ntm model path' Is the ntm model path I ran in advance？

**Comment by yuewang-cuhk** [comment]
Yes, you need to pre-train a NTM model first, then integrate it with the seq2seq for joint training. I am not sure why this error occurs given the provided information.
